import type { Metadata } from "next";
import { Coiny, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TanstackProvider from "@/provider/tanstackProvider";
import SessionWrapper from "@/provider/session-wrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const coiny = Coiny({
  variable: "--font-coiny",
  subsets: ["latin"],
  weight: "400", 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${coiny.variable} antialiased`}
      >
        <SessionWrapper>


        <TanstackProvider>{children}</TanstackProvider>
        </SessionWrapper>
      </body>
    </html>
  );
}
