import type { Metadata } from "next";
import { Coiny, Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import TanstackProvider from "@/provider/tanstackProvider";
import SessionWrapper from "@/provider/session-wrapper";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const coiny = Coiny({
  variable: "--font-coiny",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Live from snack time",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${geistSans.variable} ${geistMono.variable} ${coiny.variable} font-poppins antialiased`}
      >
        <SessionWrapper>
          <TanstackProvider>{children}</TanstackProvider>
          <Toaster
            position="top-center"
            offset={16}
            gap={12}
            visibleToasts={3}
            duration={5000}
            richColors
            closeButton
            expand={false}
          />
        </SessionWrapper>
      </body>
    </html>
  );
}
